# Generated by Django 4.0 on 2021-12-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_spaces', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
